Update Functions To Use @property & setter Structure
adafruit/Adafruit_CircuitPython_VEML6070 pull request #5
Opened 2018-09-12 22:34 UTC by sommersoft

Updated to be closer to the new VEML6075 library's usage. There are still differences, but I don't think they'll need to be carbon copies. I can be persuaded though.. 😄

2018-09-13 19:25 UTC, tannewt requested changes
Thanks! Just a couple comments about this area of the code. (Not necessarily the changes)

2018-09-13 19:25 UTC, tannewt commented on adafruit_veml6070.py
> +    def ack(self, new_ack=False):
no need for the default value since its a setter.

2018-09-13 19:25 UTC, tannewt commented on adafruit_veml6070.py
>              raise ValueError("ACK must be 'True' or 'False'.")
This should be replaced with a `new_ack = bool(new_ack)` because python's truthiness is broader than the bool type. For example, empty list is False. https://docs.python.org/3/library/stdtypes.html#truth-value-testing

2018-09-13 19:25 UTC, tannewt commented on adafruit_veml6070.py
> +        return self._ack_thd
Could we read this back instead of caching it?

2018-09-15 00:25 UTC, sommersoft commented on adafruit_veml6070.py
> +        return self._ack_thd
I had thought about this for all of ACK, ACK Threshold, and the Integration Time. However, I didn't think it was possible since the datasheet says this, and doesn't mention a return value for the command address:
```
The VEML6070 has one slave address used for write functions (command) and two slave
addresses used for read functions (UV data LSB and MSB). 
```
But, I went ahead and tried it with this:
```
# self.i2c_cmd = I2CDevice(i2c_bus, _VEML6070_ADDR_CMD)
def _read_cmd(self):
        read_buf = bytearray(2)
        with self.i2c_cmd as i2c_cmd:
            i2c_cmd.readinto(read_buf)
        return read_buf
```
And the result seems to match datasheet:
```
>>> import board, busio, adafruit_veml6070
>>> i2c = busio.I2C(board.SCL, board.SDA)
>>> uv = adafruit_veml6070.VEML6070(i2c)
>>> uv.ack
0
>>> uv._read_cmd()
bytearray(b'\x00\xff')
>>> uv.ack = True
>>> uv._read_cmd()
bytearray(b'\x00\xff')
>>>
```

2018-09-17 04:42 UTC, ladyada approved these changes

2018-09-17 04:43 UTC, ladyada commented
looks ok to me, @tannewt looks like the change you wanted can't be done?

2018-09-17 05:13 UTC, tannewt commented on adafruit_veml6070.py
> +        return self._ack_thd
Ok, thanks for trying! Caching is fine.

2018-09-17 05:13 UTC, tannewt approved these changes

2018-09-17 05:13 UTC, merged