Fixes issue #7 whereby the read method should be renamed to raw_uv
adafruit/Adafruit_CircuitPython_VEML6070 pull request #8
Opened 2019-05-08 18:06 UTC by WindFishDiety

Addressing #7 
Updated code, comments and sample code.
Testing would be required

2019-05-09 01:18 UTC, caternuson requested changes
Looks good. My suggestions are essentially cosmetic.

2019-05-09 01:18 UTC, caternuson commented on adafruit_veml6070.py
> +    def raw_uv(self):
How about `uv_raw`? That'd be more inline with the VEML6075 that has `uva` and `uvb` properties.

2019-05-09 01:18 UTC, caternuson commented on adafruit_veml6070.py
> +        uv_buf = bytearray(2)
This buffer is just used locally and could be named anything. Naming if just `buf` or `buffer` might be better visually, so it doesn't get confused with the property name.

2019-05-09 01:18 UTC, caternuson commented on adafruit_veml6070.py
> +        uvi = uv_buf[1] << 8 | uv_buf[0]
This variable doesn't get used, so could be combined on the return line:
```python
return uv_buf[1] << 8 | uv_buf[0]
```

2019-05-09 02:10 UTC, sommersoft submitted a review, later dismissed
Looks good. Thanks for the fix @WindFishDiety!

2019-05-10 01:31 UTC, WindFishDiety commented
Hey thanks for letting me participate in the pycon sprints.

2019-05-11 05:10 UTC, caternuson approved these changes
Yep, thanks. Looks good!

2019-05-11 05:10 UTC, merged